### ISSUE TITLE
Invalid character in csv

### ISSUE THREAD

**Issue by anaerobeth** [washingtonpost/data-inaugural-committee#7]
Invalid byte sequence in UTF-8 in `city` column for `transaction id` 451:

<img width="602" alt="screen shot 2017-04-20 at 11 45 20 pm" src="https://cloud.githubusercontent.com/assets/3663322/25262153/3007043c-2624-11e7-846e-2b1c0ff1e03e.png">

**Comment by stevenrich-zz** [comment]
thanks, will fix!
